apiVersion: v1
kind: Service
metadata:
  name: front-metrics-nodeport
  labels:
    app: front
  namespace: healthyreal
spec:
  type: NodePort
  selector:
    app: front
  ports:
    - name: metrics
      port: 8113
      targetPort: metrics
      nodePort: 3113

